import { useState } from "react";
import GrainOverlay from "../../components/art/GrainOverlay";
import Scrollytelling from "../../components/scrolly/Scrollytelling";
import Reveal from "../../components/scrolly/Reveal";
import Footer from "../../components/layout/Footer";
import "./happy-travelers.css";

/**
 * Each stanza is one scroll step. `img` is the base filename (no suffix) of the
 * photo that pins in the sticky stage while the stanza reads; leave it undefined
 * to show a blank framed slot instead. `slot` is a short hint for where an image
 * belongs while a frame is still blank.
 *
 * Each photo ships as three variants generated by `scripts/gen-images.mjs`:
 *   -lqip.jpg (32px blur placeholder), -sm.jpg (768px), -md.jpg (1280px).
 */
interface Stanza {
  lines: string[];
  img?: string;
  slot: string;
}

/** self-hosted photos live in public/images/happy-travelers/ */
const IMG = import.meta.env.BASE_URL + "images/happy-travelers/";

/**
 * Progressive photo: a tiny blurred placeholder paints immediately, `srcset`
 * hands phones the small file and desktop the larger one, and the full image
 * fades in once decoded — so a slow network still shows something at once.
 */
function FrameImage({ base }: { base: string }) {
  const [loaded, setLoaded] = useState(false);
  return (
    <div className="travelers__pimg">
      <img className="travelers__pimg-lqip" src={`${IMG}${base}-lqip.jpg`} alt="" aria-hidden />
      <img
        className={`travelers__pimg-full${loaded ? " is-loaded" : ""}`}
        src={`${IMG}${base}-md.jpg`}
        srcSet={`${IMG}${base}-sm.jpg 768w, ${IMG}${base}-md.jpg 1280w`}
        sizes="(max-width: 760px) 82vw, 42vw"
        alt=""
        decoding="async"
        onLoad={() => setLoaded(true)}
      />
    </div>
  );
}

const STANZAS: Stanza[] = [
  {
    img: "01-pasture-dawn",
    slot: "waking — soft light, a horse in the field",
    lines: [
      "breeze, sweet as a mother's hug.",
      "the voices of my family drift up in my soft slumber.",
      "i wake to the dark horse still standing and a black bird, came up to say hello",
    ],
  },
  {
    img: "02-horse-blackbird",
    slot: "the only words — horse, bird, honeybee",
    lines: [
      "these are the only words i've got— dark horse, black bird, the fluffy kind of honeybee",
      "i'm sure my sister would know the names of",
    ],
  },
  {
    img: "03-town-ruin",
    slot: "the town — cottages, someone else's finished work",
    lines: [
      "i'm sure many sat here before and actually did something, composed lullabies, mysteries, essays with depth and any kind of conviction",
      "i'm sure many finished novels, biked hundreds of miles, because this town is begging you to think, us to listen",
    ],
  },
  {
    img: "04-village-field",
    slot: "too much time — grass, flowers along the shoreline",
    lines: [
      "in between pleasant pastures and quaint cottages all i think is there is too much time.",
      "the way the morning light blinds us,",
      "there are too many— pages",
      "to will myself to write, anxieties",
      "to burn from my brain, tears",
      "to cry for no reason, before this soft grass, sweet hum, yellow flowers painted along the shoreline can speak to me",
    ],
  },
  {
    img: "05-cliff-tower",
    slot: "the turn — a thousand ravens leaving the trees",
    lines: [
      "tonight, when i've finally released my tears, a thousand ravens emerge from the trees.",
      "they scream, and the happy travelers cover their ears.",
    ],
  },
  {
    img: "06-cliffs-sea",
    slot: "the ravens speak — rocky cliffs, deep water, rain",
    lines: [
      "“did you not believe?",
      "you must not be healed to listen.",
      "you thought we could not hear?",
      "this town is more rocky cliffs than sunsets, more deep waters than shore.",
      "we love the rain, my dear.”",
    ],
  },
  {
    // final beat: the cliffs held with no text, so the last stanza can scroll
    // all the way up and the photo stands alone before the footer.
    img: "06-cliffs-sea",
    slot: "",
    lines: [],
  },
];

export default function HappyTravelers() {
  const steps = STANZAS.map((stanza, i) => (
    <div key={i} className="travelers__stanza">
      {stanza.lines.map((line, j) => (
        <Reveal as="p" key={j} delay={j * 0.12} y={16} className="travelers__line">
          {line}
        </Reveal>
      ))}
    </div>
  ));

  return (
    <div className="travelers">
      {/* title */}
      <header className="travelers__title-card">
        <p className="travelers__kicker">july 23rd, 2026</p>
        <h1 className="travelers__title">happy travelers</h1>
        <div className="travelers__rule" />
      </header>

      <Scrollytelling
        className="travelers__scrolly"
        align="right"
        renderSticky={(active) => {
          const stanza = STANZAS[active] ?? STANZAS[0];
          return (
            <div className="travelers__stage">
              <div className="travelers__frame">
                {stanza.img ? (
                  <FrameImage base={stanza.img} />
                ) : (
                  /* blank space for a picture, added later */
                  <div className="travelers__frame-blank">
                    <span className="travelers__frame-hint">{stanza.slot}</span>
                  </div>
                )}
              </div>
              <div className="travelers__vignette" />
              <GrainOverlay opacity={0.1} blend="soft-light" />
            </div>
          );
        }}
        steps={steps}
      />

      <Footer tone="dark" />
    </div>
  );
}
